## static_countries
UPDATE static_countries SET cn_short_it='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_it='Emirati Arabi Uniti' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_it='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_it='Antigua e Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_it='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_it='Albania' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_it='Armenia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_it='Antille Olandesi' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_it='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_it='Antartide' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_it='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_it='Samoa Americane' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_it='Austria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_it='Australia' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_it='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_it='Azerbaigian' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_it='Bosnia Erzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_it='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_it='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_it='Belgio' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_it='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_it='Bulgaria' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_it='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_it='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_it='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_it='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_it='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_it='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_it='Brasile' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_it='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_it='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_it='Isola Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_it='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_it='Bielorussia' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_it='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_it='Canada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_it='Isole Cocos (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_it='Repubblica Democratica del Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_it='Repubblica Centrafricana' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_it='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_it='Svizzera' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_it='Costa d’Avorio' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_it='Isole Cook' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_it='Cile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_it='Camerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_it='Cina' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_it='Colombia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_it='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_it='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_it='Capo Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_it='Isola di Christmas' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_it='Cipro' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_it='Repubblica Ceca' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_it='Germania' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_it='Gibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_it='Danimarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_it='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_it='Repubblica Dominicana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_it='Algeria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_it='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_it='Estonia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_it='Egitto' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_it='Sahara Occidentale' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_it='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_it='Spagna' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_it='Etiopia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_it='Finlandia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_it='Figi' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_it='Isole Falkland' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_it='Micronesia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_it='Isole Faroe' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_it='Francia' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_it='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_it='Regno Unito' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_it='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_it='Georgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_it='Guiana Francese' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_it='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_it='Gibilterra' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_it='Groenlandia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_it='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_it='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_it='Guadalupa' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_it='Guinea Equatoriale' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_it='Grecia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_it='Georgia del Sud e Isole Sandwich del Sud' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_it='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_it='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_it='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_it='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_it='Regione Amministrativa Speciale di Hong Kong, Cina' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_it='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_it='Croazia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_it='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_it='Ungheria' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_it='Indonesia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_it='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_it='Israele' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_it='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_it='Territorio Britannico dell’Oceano Indiano' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_it='Iraq' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_it='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_it='Islanda' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_it='Italia' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_it='Giamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_it='Giordania' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_it='Giappone' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_it='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_it='Kirghizistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_it='Cambogia' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_it='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_it='Comore' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_it='Saint Kitts e Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_it='Corea del Nord' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_it='Corea del Sud' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_it='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_it='Isole Cayman' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_it='Kazakistan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_it='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_it='Libano' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_it='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_it='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_it='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_it='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_it='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_it='Lituania' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_it='Lussemburgo' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_it='Lettonia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_it='Libia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_it='Marocco' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_it='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_it='Moldavia' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_it='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_it='Isole Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_it='Macedonia, Repubblica' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_it='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_it='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_it='Mongolia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_it='Regione Amministrativa Speciale di Macao, Cina' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_it='Isole Marianne Settentrionali' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_it='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_it='Mauritania' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_it='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_it='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_it='Maurizio' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_it='Maldive' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_it='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_it='Messico' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_it='Malaysia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_it='Mozambico' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_it='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_it='Nuova Caledonia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_it='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_it='Isola Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_it='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_it='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_it='Paesi Bassi' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_it='Norvegia' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_it='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_it='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_it='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_it='Nuova Zelanda' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_it='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_it='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_it='Perù' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_it='Polinesia Francese' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_it='Papua Nuova Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_it='Filippine' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_it='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_it='Polonia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_it='Saint Pierre e Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_it='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_it='Portorico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_it='Portogallo' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_it='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_it='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_it='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_it='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_it='Romania' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_it='Federazione Russa' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_it='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_it='Arabia Saudita' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_it='Isole Solomon' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_it='Seychelles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_it='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_it='Svezia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_it='Singapore' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_it='Sant’Elena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_it='Slovenia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_it='Svalbard e Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_it='Slovacchia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_it='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_it='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_it='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_it='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_it='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_it='São Tomé e Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_it='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_it='Siria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_it='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_it='Isole Turks e Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_it='Ciad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_it='Territori australi francesi' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_it='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_it='Tailandia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_it='Tagikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_it='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_it='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_it='Tunisia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_it='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_it='Timor Est' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_it='Turchia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_it='Trinidad e Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_it='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_it='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_it='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_it='Ucraina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_it='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_it='Isole Minori lontane dagli Stati Uniti' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_it='Stati Uniti' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_it='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_it='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_it='Vaticano' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_it='Saint Vincent e Grenadines' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_it='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_it='Isole Vergini Britanniche' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_it='Isole Vergini Americane' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_it='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_it='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_it='Wallis e Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_it='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_it='Yemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_it='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_it='Sudafrica' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_it='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_it='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_it='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_it='Serbia e Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_it='Isole Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_it='Isole Heard ed Isole McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_it='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_it='Serbia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_it='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_it='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_it='Isola di Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_it='Saint Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_it='Saint-Barthélemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_it='Bonaire, Sint Eustatius, Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_it='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_it='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_it='Sudan del Sud' WHERE cn_iso_2='SS';

## static_currencies
UPDATE static_currencies SET cu_name_it='Dirham degli Emirati Arabi Uniti',cu_sub_name_it='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_it='Lek Albanese',cu_sub_name_it='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_it='Dram Armeno',cu_sub_name_it='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_it='Fiorino delle Antille Olandesi',cu_sub_name_it='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_it='Kwanza Angolano',cu_sub_name_it='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_it='Peso Argentino',cu_sub_name_it='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_it='Dollaro Australiano',cu_sub_name_it='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_it='Fiorino di Aruba',cu_sub_name_it='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_it='Manat Azero',cu_sub_name_it='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_it='Marco Conv. Bosnia-Erzegovina',cu_sub_name_it='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_it='Dollaro di Barbados',cu_sub_name_it='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_it='Taka Bangladese',cu_sub_name_it='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_it='Nuovo Lev Bulgaro',cu_sub_name_it='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_it='Dinaro del Bahraini',cu_sub_name_it='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_it='Franco del Burundi',cu_sub_name_it='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_it='Dollaro delle Bermuda',cu_sub_name_it='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_it='Dollaro del Brunei',cu_sub_name_it='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_it='Boliviano',cu_sub_name_it='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_it='Real Brasiliano',cu_sub_name_it='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_it='Dollaro delle Bahamas',cu_sub_name_it='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_it='Ngultrum Butanese',cu_sub_name_it='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_it='Pula del Botswana',cu_sub_name_it='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_it='Rublo Bielorussia',cu_sub_name_it='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_it='Dollaro Belize',cu_sub_name_it='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_it='Dollaro Canadese',cu_sub_name_it='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_it='Franco Congolese',cu_sub_name_it='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_it='Franco Svizzero',cu_sub_name_it='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_it='Peso Cileno',cu_sub_name_it='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_it='Renmimbi Cinese',cu_sub_name_it='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_it='Peso Colombiano',cu_sub_name_it='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_it='Colón Costaricano',cu_sub_name_it='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_it='Peso Cubano',cu_sub_name_it='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_it='Escudo del Capo Verde',cu_sub_name_it='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_it='Sterlina Cipriota',cu_sub_name_it='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_it='Corona Ceca',cu_sub_name_it='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_it='Franco Gibutiano',cu_sub_name_it='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_it='Corona Danese',cu_sub_name_it='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_it='Peso Dominicano',cu_sub_name_it='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_it='Dinaro Algerino',cu_sub_name_it='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_it='Corona dell’Estonia',cu_sub_name_it='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_it='Sterlina Egiziana',cu_sub_name_it='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_it='Nakfa Eritreo',cu_sub_name_it='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_it='Birr Etiopico',cu_sub_name_it='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_it='Euro',cu_sub_name_it='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_it='Dollaro delle Figi',cu_sub_name_it='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_it='Sterlina delle Falkland',cu_sub_name_it='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_it='Sterlina Inglese',cu_sub_name_it='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_it='Lari Georgiano',cu_sub_name_it='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_it='Cedi del Ghana',cu_sub_name_it='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_it='Sterlina di Gibilterra',cu_sub_name_it='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_it='Dalasi del Gambia',cu_sub_name_it='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_it='Franco della Guinea',cu_sub_name_it='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_it='Quetzal Guatemalteco',cu_sub_name_it='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_it='Peso della Guinea-Bissau',cu_sub_name_it='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_it='Dollaro della Guyana',cu_sub_name_it='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_it='Dollaro di Hong Kong',cu_sub_name_it='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_it='Lempira Hoduregno',cu_sub_name_it='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_it='Kuna Croata',cu_sub_name_it='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_it='Gourde Haitiano',cu_sub_name_it='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_it='Fiorino Ungherese',cu_sub_name_it='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_it='Rupia Indiana',cu_sub_name_it='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_it='Nuovo sheqel israeliano',cu_sub_name_it='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_it='Rupia Indiana',cu_sub_name_it='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_it='Dinaro Iracheno',cu_sub_name_it='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_it='Rial Iraniano',cu_sub_name_it='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_it='Corona Islandese',cu_sub_name_it='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_it='Dollaro Giamaicano',cu_sub_name_it='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_it='Dinaro Giordano',cu_sub_name_it='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_it='Yen Giapponese',cu_sub_name_it='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_it='Scellino Keniota',cu_sub_name_it='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_it='Som  Kirghiso',cu_sub_name_it='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_it='Riel Cambogiano',cu_sub_name_it='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_it='Franco Comoriano',cu_sub_name_it='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_it='Won Nordcoreano',cu_sub_name_it='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_it='Won Sudcoreano',cu_sub_name_it='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_it='Dinaro Kuwaitiano',cu_sub_name_it='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_it='Dollaro delle Isole Cayman',cu_sub_name_it='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_it='Tenge Kazaco',cu_sub_name_it='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_it='Kip Laotiano',cu_sub_name_it='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_it='Sterlina Libanese',cu_sub_name_it='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_it='Rupia di Sri Lanka',cu_sub_name_it='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_it='Dollaro Liberiano',cu_sub_name_it='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_it='Loti del Lesotho',cu_sub_name_it='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_it='Lita Lituana',cu_sub_name_it='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_it='Lat Lettone',cu_sub_name_it='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_it='Dinaro Libico',cu_sub_name_it='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_it='Dirham Marocchino',cu_sub_name_it='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_it='Leu Moldavo',cu_sub_name_it='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_it='Dinaro Macedone',cu_sub_name_it='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_it='Kyat di Myanmar',cu_sub_name_it='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_it='Tugrik Mongolo',cu_sub_name_it='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_it='Pataca di Macao',cu_sub_name_it='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_it='Ouguiya della Mauritania',cu_sub_name_it='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_it='Lira Maltese',cu_sub_name_it='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_it='Rupia Mauriziana',cu_sub_name_it='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_it='Rufiyaa delle Maldive',cu_sub_name_it='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_it='Kwacha Malawiano',cu_sub_name_it='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_it='Peso Messicano',cu_sub_name_it='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_it='Ringgit della Malesia',cu_sub_name_it='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_it='Metical del Mozambico',cu_sub_name_it='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_it='Dollaro Namibiano',cu_sub_name_it='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_it='Naira Nigeriana',cu_sub_name_it='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_it='Córdoba oro nicaraguense',cu_sub_name_it='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_it='Corona Norvegese',cu_sub_name_it='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_it='Rupia Nepalese',cu_sub_name_it='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_it='Dollaro Neozelandese',cu_sub_name_it='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_it='Rial Omanita',cu_sub_name_it='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_it='Balboa di Panama',cu_sub_name_it='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_it='Sol Nuevo Peruviano',cu_sub_name_it='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_it='Kina della Papua Nuova Guinea',cu_sub_name_it='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_it='Peso delle Filippine',cu_sub_name_it='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_it='Rupia del Pakistan',cu_sub_name_it='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_it='Zloty Polacco',cu_sub_name_it='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_it='Guarani del Paraguay',cu_sub_name_it='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_it='Rial del Qatar',cu_sub_name_it='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_it='Leu della Romania',cu_sub_name_it='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_it='Rublo Russo',cu_sub_name_it='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_it='Franco Ruandese',cu_sub_name_it='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_it='Ryal Saudita',cu_sub_name_it='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_it='Dollaro delle Isole Solomon',cu_sub_name_it='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_it='Rupia delle Seychelles',cu_sub_name_it='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_it='Sterlina Sudanese',cu_sub_name_it='' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_it='Corona Svedese',cu_sub_name_it='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_it='Dollaro di Singapore',cu_sub_name_it='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_it='Sterlina di Sant’Elena',cu_sub_name_it='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_it='Tallero Sloveno',cu_sub_name_it='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_it='Corona Slovacca',cu_sub_name_it='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_it='Leone della Sierra Leone',cu_sub_name_it='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_it='Scellino Somalo',cu_sub_name_it='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_it='Dobra di São Tomé e Principe',cu_sub_name_it='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_it='Colón Salvadoregno',cu_sub_name_it='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_it='Sterlina Siriana',cu_sub_name_it='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_it='Lilangeni dello Swaziland',cu_sub_name_it='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_it='Baht Tailandese',cu_sub_name_it='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_it='Somoni del Tajikistan',cu_sub_name_it='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_it='Manat Turkmeno',cu_sub_name_it='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_it='Dinaro Tunisino',cu_sub_name_it='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_it='Paʻanga di Tonga',cu_sub_name_it='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_it='Dollaro di Trinidad e Tobago',cu_sub_name_it='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_it='Nuovo dollaro taiwanese',cu_sub_name_it='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_it='Scellino della Tanzania',cu_sub_name_it='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_it='Hrivna Ucraina',cu_sub_name_it='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_it='Scellino Ugandese',cu_sub_name_it='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_it='Dollaro Statunitense',cu_sub_name_it='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_it='Peso Uruguayo uruguaiano',cu_sub_name_it='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_it='Sum dell’Uzbekistan',cu_sub_name_it='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_it='Bolivar Venezuelano',cu_sub_name_it='' WHERE cu_iso_3='VEF';
UPDATE static_currencies SET cu_name_it='Dong Vietnamita',cu_sub_name_it='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_it='Vatu di Vanuatu',cu_sub_name_it='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_it='Tala della Samoa Occidentale',cu_sub_name_it='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_it='Franco CFA BEAC',cu_sub_name_it='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_it='Dollaro dei Caraibi Orientali',cu_sub_name_it='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_it='Franco CFA BCEAO',cu_sub_name_it='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_it='Franco CFP',cu_sub_name_it='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_it='Rial dello Yemen',cu_sub_name_it='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_it='Rand Sudafricano',cu_sub_name_it='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_it='Kwacha dello Zambia',cu_sub_name_it='' WHERE cu_iso_3='ZMW';
UPDATE static_currencies SET cu_name_it='Dollaro dello Zimbabwe',cu_sub_name_it='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_it='Afgani',cu_sub_name_it='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_it='Dinaro Serbo',cu_sub_name_it='' WHERE cu_iso_3='RSD';
UPDATE static_currencies SET cu_name_it='Ariary Malgascio',cu_sub_name_it='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_it='Dollaro Surinamese',cu_sub_name_it='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_it='Lira Turca',cu_sub_name_it='' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_it='Sterlina Sudsudanese',cu_sub_name_it='' WHERE cu_iso_3='SSP';
UPDATE static_currencies SET cu_name_it='Cedi Ghanese',cu_sub_name_it='' WHERE cu_iso_3='GHS';
UPDATE static_currencies SET cu_name_it='Metical',cu_sub_name_it='' WHERE cu_iso_3='MZN';
UPDATE static_currencies SET cu_name_it='Leu Romeno',cu_sub_name_it='' WHERE cu_iso_3='RON';
UPDATE static_currencies SET cu_name_it='Manat Turkmeno',cu_sub_name_it='' WHERE cu_iso_3='TMT';
## static_languages
UPDATE static_languages SET lg_name_it='abkhazian' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='afar' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='afrikaans' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='albanese' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='amarico' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='arabo' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='armeno' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='assamese' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='aymara' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='azerbaigiano' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='baschiro' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='basco' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bengalese' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='dzongkha' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bihari' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bislama' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bretone' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bulgaro' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='birmano' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bielorusso' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='khmer' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='catalano' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='zhuang' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='cinese' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_it='corso' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='croato' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ceco' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='danese' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='olandese' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='inglese' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='esperanto' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='estone' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='faroese' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='persiano' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='figiano' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='finlandese' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='francese' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='frisone' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='galiziano' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='gaelico scozzese' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='manx' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='georgiano' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tedesco' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='greco' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kalaallisut' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='guarana' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='gujarati' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='haussa' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ebraico' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='hindi' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ungherese' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='islandese' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='indonesiano' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='interlingua' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='interlingue' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='inuktitut' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='inupiak' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='irlandese' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='italiano' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='giapponese' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kannada' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kashmiri' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kazako' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kinyarwanda' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kirghiso' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='rundi' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='coreano' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='curdo' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='lao' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='latino' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='lettone' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='lingala' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='lituano' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='macedone' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='malgascio' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='malese' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='malayalam' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='maltese' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='maori' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='marathi' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='moldavo' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='mongolo' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='nauru' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='nepalese' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='norvegese' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='occitano (post 1500); provenza' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='oriya' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='oromo' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='pashto' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='polacco' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='portoghese' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='punjabi' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='quechua' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='lingua rhaeto-romance' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='rumeno' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='russo' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='samoano' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sango' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sanscrito' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='serbo' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sotho del sud' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tswana' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='shona' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sindhi' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='singalese' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='swati' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='slovacco' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sloveno' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='somalo' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='spagnolo' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sundanese' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='swahili' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='svedese' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tagalog' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tagicco' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tamil' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tatarico' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='telugu' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='thai' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tibetano' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tigrinya' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tonga (Isole Tonga)' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='tsonga' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='turco' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='turcomanno' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ci' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='uigurico' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ucraino' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='urdu' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='usbeco' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='vietnamita' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='volapük' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='gallese' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='volof' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='xosa' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='yiddish' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='yoruba' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='zulu' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bosniaco' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='avestan' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='akan' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='aragonese' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='avaro' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='bambara' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ceceno' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='chamorro' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='cree' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='slavo della Chiesa' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='chuvash' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='divehi' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ewe' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='fulah' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='hiri motu' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='haitiano' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='herero' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='igbo' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sichuan yi' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ido' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='giavanese' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kongo' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kikuyu' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kuanyama' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='kanuri' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='komi' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='cornico' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='lussemburghese' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ganda' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='limburgese' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='luba-katanga' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='marshallese' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='norvegese bokmål' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ndebele del nord' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ndonga' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='norvegese nynorsk' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ndebele del sud' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='navajo' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='nyanja; chichewa; chewa' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ojibwa' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='ossetico' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='pali' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sardo' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='sami del nord' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='taitiano' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='venda' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='vallone' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_it='portoghese' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_it='cinese' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_it='' WHERE lg_iso_2='FR' AND lg_country_iso_2='CA';
UPDATE static_languages SET lg_name_it='' WHERE lg_iso_2='TL' AND lg_country_iso_2='PH';
UPDATE static_languages SET lg_name_it='' WHERE lg_iso_2='SR' AND lg_country_iso_2='ME';
## static_territories
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='34';
UPDATE static_territories SET tr_name_it='' WHERE tr_iso_nr='419';
## static country zones: swiss cantons
UPDATE static_country_zones SET zn_name_it='Argovia' WHERE zn_country_iso_3='CHE' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_it='Appenzello Interno' WHERE zn_country_iso_3='CHE' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_it='Appenzello Esterno' WHERE zn_country_iso_3='CHE' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_it='Basilea Campagna' WHERE zn_country_iso_3='CHE' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_it='Basilea Città' WHERE zn_country_iso_3='CHE' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_it='Berna' WHERE zn_country_iso_3='CHE' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_it='Friburgo' WHERE zn_country_iso_3='CHE' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_it='Ginevra' WHERE zn_country_iso_3='CHE' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_it='Giura' WHERE zn_country_iso_3='CHE' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_it='Glarona' WHERE zn_country_iso_3='CHE' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_it='Grigioni' WHERE zn_country_iso_3='CHE' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_it='Lucerna' WHERE zn_country_iso_3='CHE' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_it='Neuchâtel' WHERE zn_country_iso_3='CHE' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_it='Nidvaldo' WHERE zn_country_iso_3='CHE' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_it='Obvaldo' WHERE zn_country_iso_3='CHE' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_it='Sciaffusa' WHERE zn_country_iso_3='CHE' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_it='Svitto' WHERE zn_country_iso_3='CHE' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_it='Soletta' WHERE zn_country_iso_3='CHE' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_it='San Gallo' WHERE zn_country_iso_3='CHE' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_it='Ticino' WHERE zn_country_iso_3='CHE' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_it='Turgovia' WHERE zn_country_iso_3='CHE' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_it='Uri' WHERE zn_country_iso_3='CHE' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_it='Vaud' WHERE zn_country_iso_3='CHE' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_it='Vallese' WHERE zn_country_iso_3='CHE' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_it='Zugo' WHERE zn_country_iso_3='CHE' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_it='Zurigo' WHERE zn_country_iso_3='CHE' AND zn_code='ZH';
